// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenJustice.BrazilExtractor.Data;

#nullable disable

namespace OpenJustice.BrazilExtractor.Web.Data.Migrations
{
    [DbContext(typeof(OcrTrackingDbContext))]
    [Migration("20260303035156_InitialOcrTracking")]
    partial class InitialOcrTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("OpenJustice.BrazilExtractor.Data.OcrPageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharactersExtracted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionDate")
                        .HasDatabaseName("IX_OcrPageRecords_ExecutionDate");

                    b.HasIndex("PdfPath")
                        .HasDatabaseName("IX_OcrPageRecords_PdfPath");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_OcrPageRecords_Status");

                    b.HasIndex("ExecutionDate", "Status")
                        .HasDatabaseName("IX_OcrPageRecords_Pending");

                    b.HasIndex("ExecutionDate", "PdfPath", "PageNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_OcrPageRecords_CompositeKey");

                    b.ToTable("OcrPageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
