// <auto-generated />
using System;
using AtrocidadesRSS.Generator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtrocidadesRSS.Generator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301175321_AddCompositeIndexes")]
    partial class AddCompositeIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccusedAddress")
                        .HasColumnType("text");

                    b.Property<int?>("AccusedAge")
                        .HasColumnType("integer");

                    b.Property<int>("AccusedConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("AccusedDocument")
                        .HasColumnType("text");

                    b.Property<string>("AccusedGender")
                        .HasColumnType("text");

                    b.Property<string>("AccusedName")
                        .HasColumnType("text");

                    b.Property<string>("AccusedNationality")
                        .HasColumnType("text");

                    b.Property<string>("AccusedProfession")
                        .HasColumnType("text");

                    b.Property<string>("AccusedRelationshipToVictim")
                        .HasColumnType("text");

                    b.Property<string>("AccusedSocialName")
                        .HasColumnType("text");

                    b.Property<string>("AnonymizationStatus")
                        .HasColumnType("text");

                    b.Property<int>("CaseTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("County")
                        .HasColumnType("text");

                    b.Property<string>("Court")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CrimeConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("CrimeCoordinates")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CrimeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrimeDescription")
                        .HasColumnType("text");

                    b.Property<string>("CrimeLocationAddress")
                        .HasColumnType("text");

                    b.Property<string>("CrimeLocationCity")
                        .HasColumnType("text");

                    b.Property<string>("CrimeLocationState")
                        .HasColumnType("text");

                    b.Property<string>("CrimeSubtype")
                        .HasColumnType("text");

                    b.Property<int>("CrimeTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("CuratorId")
                        .HasColumnType("text");

                    b.Property<string>("CurrentPhase")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EstimatedCrimeDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSensitiveContent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("JudicialConfidence")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("JudicialReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JudicialStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MainCategory")
                        .HasColumnType("text");

                    b.Property<string>("Motivation")
                        .HasColumnType("text");

                    b.Property<int>("NumberOfAccused")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfVictims")
                        .HasColumnType("integer");

                    b.Property<string>("PendingAppeals")
                        .HasColumnType("text");

                    b.Property<string>("Premeditation")
                        .HasColumnType("text");

                    b.Property<string>("ProcessNumber")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sentence")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentencingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VictimAge")
                        .HasColumnType("integer");

                    b.Property<int>("VictimConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("VictimGender")
                        .HasColumnType("text");

                    b.Property<string>("VictimName")
                        .HasColumnType("text");

                    b.Property<string>("VictimNationality")
                        .HasColumnType("text");

                    b.Property<string>("VictimProfession")
                        .HasColumnType("text");

                    b.Property<string>("VictimRelationshipToAccused")
                        .HasColumnType("text");

                    b.Property<string>("WeaponUsed")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccusedName");

                    b.HasIndex("CaseTypeId");

                    b.HasIndex("CrimeDate");

                    b.HasIndex("CrimeLocationCity");

                    b.HasIndex("CrimeLocationState");

                    b.HasIndex("JudicialStatusId");

                    b.HasIndex("ReferenceCode")
                        .IsUnique();

                    b.HasIndex("VictimName");

                    b.HasIndex("CrimeLocationState", "CrimeDate")
                        .HasDatabaseName("IX_Cases_CrimeLocationState_CrimeDate");

                    b.HasIndex("CrimeTypeId", "JudicialStatusId")
                        .HasDatabaseName("IX_Cases_CrimeTypeId_JudicialStatusId");

                    b.ToTable("Cases", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cases_AccusedConfidence", "AccusedConfidence >= 0 AND AccusedConfidence <= 100");

                            t.HasCheckConstraint("CK_Cases_CrimeConfidence", "CrimeConfidence >= 0 AND CrimeConfidence <= 100");

                            t.HasCheckConstraint("CK_Cases_JudicialConfidence", "JudicialConfidence >= 0 AND JudicialConfidence <= 100");

                            t.HasCheckConstraint("CK_Cases_VictimConfidence", "VictimConfidence >= 0 AND VictimConfidence <= 100");
                        });
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CaseFieldHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<int>("ChangeConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CuratorId")
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("ChangedAt");

                    b.ToTable("CaseFieldHistory", null, t =>
                        {
                            t.HasCheckConstraint("CK_CaseFieldHistory_Confidence", "ChangeConfidence >= 0 AND ChangeConfidence <= 100");
                        });
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CaseTag", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CaseId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("CaseTags", (string)null);
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CaseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CaseTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CaseTypes_Confidence", "Confidence >= 0 AND Confidence <= 100");
                        });
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CrimeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CrimeTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_CrimeTypes_Confidence", "Confidence >= 0 AND Confidence <= 100");
                        });
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("Forensics")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Witnesses")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Evidence", null, t =>
                        {
                            t.HasCheckConstraint("CK_Evidence_Confidence", "Confidence >= 0 AND Confidence <= 100");
                        });
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.JudicialStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JudicialStatuses", null, t =>
                        {
                            t.HasCheckConstraint("CK_JudicialStatuses_Confidence", "Confidence >= 0 AND Confidence <= 100");
                        });
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommentsCount")
                        .HasColumnType("integer");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurationNotes")
                        .HasColumnType("text");

                    b.Property<string>("OriginalLink")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Upvotes")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Sources", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sources_Confidence", "Confidence >= 0 AND Confidence <= 100");
                        });
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Case", b =>
                {
                    b.HasOne("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CaseType", "CaseType")
                        .WithMany("Cases")
                        .HasForeignKey("CaseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CrimeType", "CrimeType")
                        .WithMany("Cases")
                        .HasForeignKey("CrimeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.JudicialStatus", "JudicialStatus")
                        .WithMany("Cases")
                        .HasForeignKey("JudicialStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaseType");

                    b.Navigation("CrimeType");

                    b.Navigation("JudicialStatus");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CaseFieldHistory", b =>
                {
                    b.HasOne("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Case", "Case")
                        .WithMany("FieldHistories")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CaseTag", b =>
                {
                    b.HasOne("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Case", "Case")
                        .WithMany("CaseTags")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Tag", "Tag")
                        .WithMany("CaseTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Evidence", b =>
                {
                    b.HasOne("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Case", "Case")
                        .WithMany("Evidences")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Source", b =>
                {
                    b.HasOne("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Case", "Case")
                        .WithMany("Sources")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Case", b =>
                {
                    b.Navigation("CaseTags");

                    b.Navigation("Evidences");

                    b.Navigation("FieldHistories");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CaseType", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.CrimeType", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.JudicialStatus", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("AtrocidadesRSS.Generator.Infrastructure.Persistence.Entities.Tag", b =>
                {
                    b.Navigation("CaseTags");
                });
#pragma warning restore 612, 618
        }
    }
}
